# Site settings
title: Bhumi Patel
description: Securely connect to decrypt my world in cybersecurity.
url: "https://bhumipatel15.github.io"
baseurl: ""
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bhumi Patel
user_description: With experience as a QA, Support Specialist, and SRE, I am now pursuing my Master’s in Cybersecurity at Roosevelt University. Recently completed a cybersecurity and compliance internship at SafeCHR, where I worked on HIPAA compliance, secure development practices, and documentation. Continuing to learn cloud security, compliance, and incident response to gain real-world expertise.
user_title: Cybersecurity Graduate Student
email: bhumij96official@gmail.com
# twitter_username: lorem_ipsum
linkedin_username: bhumi-j-patel
# github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

